Repository R-Type-Epitech-Nantes/R-Type, pull requests merged in 2022-11, with the labels that each got.

#284 275 add authentication system
  Client/ClientRoom.cpp
  Client/ClientRoom.hpp
  Server/Room.cpp
  Server/Room.hpp
  Server/Server.cpp
  libs/Error/Error.hpp
  libs/GraphicECS/SFML/Systems/CMakeLists.txt
  libs/GraphicECS/SFML/Systems/DrawComponents.cpp
  libs/GraphicECS/SFML/Systems/DrawComponents.hpp
  libs/GraphicECS/SFML/Systems/SfObjectFollowEntitySystem.cpp
  libs/GraphicECS/SFML/Systems/SfObjectFollowEntitySystem.hpp
  libs/GraphicECS/SFML/Systems/SfRectangleFollowEntitySystem.cpp
  libs/R-TypeLogic/EntityManipulation/CreateEntitiesFunctions/CreatePlayer.cpp
  libs/R-TypeLogic/EntityManipulation/CreateEntitiesFunctions/CreatePlayer.hpp
  libs/R-TypeLogic/Global/Components/PlayerComponent.hpp
  libs/Transisthor/Transisthor.cpp
  libs/Transisthor/Transisthor.hpp
  libs/Transisthor/TransisthorECSLogic/Server/Systems/SendNewlyCreatedToClients.cpp
  tests/unit_tests/Transisthor_tests/Transisthor_tests.cpp
  tests/unit_tests/libs_tests/GameEntityManipulation_tests/CreateEntitiesFunctions_tests/CreatePlayer_test.cpp
Labels: Network, SFML

#287 Fix Windows Execution, closes #286
  cmake/DetectCompiler.cmake
  conanfile.txt
  libs/ArgumentHandler/CMakeLists.txt
  libs/GraphicECS/SFML/CMakeLists.txt
  libs/R-TypeLogic/Server/CMakeLists.txt
Labels: Cmake, Architecture, BUG

#290 Fix the compilation problem when there is no build file #289
  build.sh
Labels: BUG

#291 277 differentiate the enemies
  Server/Room.cpp
  libs/R-TypeLogic/EntityManipulation/CreateEntitiesFunctions/CreateEnemy.cpp
  libs/R-TypeLogic/EntityManipulation/CreateEntitiesFunctions/CreateEnemy.hpp
  libs/R-TypeLogic/Global/Components/EnemyComponent.hpp
  libs/Transisthor/Transisthor.cpp
  libs/Transisthor/Transisthor.hpp
  libs/Transisthor/TransisthorECSLogic/Server/Systems/SendNewlyCreatedToClients.cpp
  tests/unit_tests/Transisthor_tests/Transisthor_tests.cpp
  tests/unit_tests/libs_tests/ECS_tests/Systems_tests/Death_System_tests.cpp
  tests/unit_tests/libs_tests/ECS_tests/Systems_tests/EnemyGoRandom_System_test.cpp
  tests/unit_tests/libs_tests/ECS_tests/Systems_tests/ShootEnemy_system_test.cpp
  tests/unit_tests/libs_tests/GameEntityManipulation_tests/CreateEntitiesFunctions_tests/CreateEnemyRandom_test.cpp
  tests/unit_tests/libs_tests/GameEntityManipulation_tests/CreateEntitiesFunctions_tests/CreateEnemy_test.cpp
Labels: E.C.S., Network, R-Type Game

#285 232 fix multiple input bug
  libs/GraphicECS/SFML/Components/CMakeLists.txt
  libs/GraphicECS/SFML/Components/IsShootingComponent.hpp
  libs/GraphicECS/SFML/Resources/RenderWindowResource.hpp
  libs/GraphicECS/SFML/Systems/InputManagement.cpp
  libs/GraphicECS/SFML/Systems/InputManagement.hpp
Labels: SFML

#293 279 differentiate enemies projectiles
  Client/ClientRoom.cpp
  Client/ClientRoom.hpp
  assets/EpiSprite/ElectricEnemyProjectileSpriteSheet.gif
  assets/EpiSprite/FireEnemyProjectileSpriteSheet.gif
  assets/EpiSprite/IceEnemyProjectileSpriteSheet.gif
  libs/GraphicECS/SFML/Resources/GraphicsTextureResource.hpp
  libs/GraphicECS/SFML/Systems/DrawComponents.cpp
  libs/R-TypeLogic/EntityManipulation/CreateEntitiesFunctions/CreateEnemyProjectile.cpp
  libs/R-TypeLogic/Global/Components/CMakeLists.txt
  libs/R-TypeLogic/Global/Components/EnemyProjectileType.hpp
  tests/unit_tests/Transisthor_tests/Transisthor_tests.cpp
  tests/unit_tests/libs_tests/GameEntityManipulation_tests/CreateEntitiesFunctions_tests/CreateEnemyProjectile_test.cpp
Labels: SFML, R-Type Game

#292 288 implement writable sfml entity
  Client/ButtonAction.cpp
  Client/ButtonAction.hpp
  Client/ClientRoom.cpp
  Client/ClientRoom.hpp
  libs/GraphicECS/SFML/Components/CMakeLists.txt
  libs/GraphicECS/SFML/Components/GraphicsTextComponent.cpp
  libs/GraphicECS/SFML/Components/SelectedComponent.hpp
  libs/GraphicECS/SFML/Components/WritableContentComponent.hpp
  libs/GraphicECS/SFML/Resources/GraphicsTextureResource.hpp
  libs/GraphicECS/SFML/Systems/DrawComponents.cpp
  libs/GraphicECS/SFML/Systems/DrawComponents.hpp
  libs/GraphicECS/SFML/Systems/InputManagement.cpp
  libs/GraphicECS/SFML/Systems/InputManagement.hpp
  libs/R-TypeLogic/EntityManipulation/ButtonManipulation/CMakeLists.txt
  libs/R-TypeLogic/EntityManipulation/ButtonManipulation/SharedResources/ButtonActionMap.cpp
  libs/R-TypeLogic/EntityManipulation/ButtonManipulation/SharedResources/ButtonActionMap.hpp
  libs/R-TypeLogic/EntityManipulation/ButtonManipulation/SharedResources/GameStates.hpp
  libs/R-TypeLogic/EntityManipulation/CreateEntitiesFunctions/CMakeLists.txt
  libs/R-TypeLogic/EntityManipulation/CreateEntitiesFunctions/CreateWritable.cpp
  libs/R-TypeLogic/EntityManipulation/CreateEntitiesFunctions/CreateWritable.hpp
  libs/R-TypeLogic/Global/Components/LayerLvL.hpp
  libs/R-TypeLogic/Global/Systems/NoAfkInMenuSystem.cpp
  tests/unit_tests/libs_tests/SFML_tests/Components/CMakeLists.txt
  tests/unit_tests/libs_tests/SFML_tests/Components/SelectedComponent_tests.cpp
  tests/unit_tests/libs_tests/SFML_tests/Components/WritableContentComponent_tests.cpp
Labels: SFML, R-Type Game

#297 296 implement 5X protocol for message transfer
  Client/ButtonAction.cpp
  libs/Communicator/Communicator.cpp
  libs/Communicator/Communicator.hpp
  libs/Communicator/Receiver.cpp
  libs/Communicator/Receiver.hpp
  libs/GraphicECS/SFML/Components/SelectedComponent.hpp
  tests/unit_tests/Communicator_tests/Communicator_tests.cpp
Labels: Network

#304 303 update protocol 17 to implement room customization
  Client/ClientRoom.cpp
  Server/Server.cpp
  libs/Communicator/Communicator.cpp
  libs/Communicator/Communicator.hpp
Labels: Network

#300 298 create writable button entity
  Client/ButtonAction.cpp
  Client/ButtonAction.hpp
  Client/ClientRoom.cpp
  Client/ClientRoom.hpp
  libs/GraphicECS/SFML/Components/AssociatedIdComponent.hpp
  libs/GraphicECS/SFML/Components/CMakeLists.txt
  libs/GraphicECS/SFML/Components/WritableButtonActionComponent.hpp
  libs/GraphicECS/SFML/Resources/GraphicsTextureResource.hpp
  libs/GraphicECS/SFML/Systems/DrawComponents.cpp
  libs/R-TypeLogic/EntityManipulation/ButtonManipulation/SharedResources/ButtonActionMap.hpp
  libs/R-TypeLogic/EntityManipulation/CreateEntitiesFunctions/CMakeLists.txt
  libs/R-TypeLogic/EntityManipulation/CreateEntitiesFunctions/CreateWritableButton.cpp
  libs/R-TypeLogic/EntityManipulation/CreateEntitiesFunctions/CreateWritableButton.hpp
  libs/R-TypeLogic/Global/Components/LayerLvL.hpp
  tests/unit_tests/libs_tests/SFML_tests/Components/AssociatedIdComponent_tests.cpp
  tests/unit_tests/libs_tests/SFML_tests/Components/CMakeLists.txt
  tests/unit_tests/libs_tests/SFML_tests/Components/WritableButtonActionComponent_tests.cpp
Labels: R-Type Game

#307 303 Add missing documentation
  libs/Communicator/Communicator.hpp
Labels: Documentation, Network

#310 301 implement chat functionality
  Client/ButtonAction.cpp
  Client/ClientRoom.cpp
  Client/ClientRoom.hpp
  Server/Room.cpp
  Server/Room.hpp
  libs/ECS/World/World.hpp
  libs/GraphicECS/SFML/Components/CMakeLists.txt
  libs/GraphicECS/SFML/Components/ChatMessageComponent.hpp
  libs/GraphicECS/SFML/Components/ChatMessageLifeComponent.hpp
  libs/GraphicECS/SFML/Systems/CMakeLists.txt
  libs/GraphicECS/SFML/Systems/DrawComponents.cpp
  libs/GraphicECS/SFML/Systems/DrawComponents.hpp
  libs/GraphicECS/SFML/Systems/RemoveChatSystem.cpp
  libs/GraphicECS/SFML/Systems/RemoveChatSystem.hpp
  libs/R-TypeLogic/EntityManipulation/CreateEntitiesFunctions/CMakeLists.txt
  libs/R-TypeLogic/EntityManipulation/CreateEntitiesFunctions/CreateChatMessage.cpp
  libs/R-TypeLogic/EntityManipulation/CreateEntitiesFunctions/CreateChatMessage.hpp
  libs/R-TypeLogic/Global/Components/LayerLvL.hpp
Labels: R-Type Game

#309 302 create login menu
  Client/ButtonAction.cpp
  Client/CMakeLists.txt
  Client/ClientRoom.cpp
  Client/ClientRoom.hpp
  Client/UserConnection.cpp
  Client/UserConnection.hpp
  Client/main.cpp
  libs/GraphicECS/SFML/Systems/DrawComponents.cpp
  libs/GraphicECS/SFML/Systems/InputManagement.cpp
Labels: SFML

#312 311 Add a database library
  conanfile.txt
  libs/CMakeLists.txt
  libs/Database/CMakeLists.txt
  libs/Database/Database.cpp
  libs/Database/Database.hpp
Labels: Architecture

#295 276 add patterns to enemies
  Client/ClientRoom.cpp
  Client/ClientRoom.hpp
  Room/Room.cpp
  assets/EpiSprite/ElectricEnemySpriteSheet.gif
  assets/EpiSprite/FireEnemySpriteSheet.gif
  assets/EpiSprite/IceEnemySpriteSheet.gif
  libs/GraphicECS/SFML/Resources/GraphicsTextureResource.hpp
  libs/GraphicECS/SFML/Systems/DrawComponents.cpp
  libs/R-TypeLogic/EntityManipulation/CreateEntitiesFunctions/CreateEnemy.cpp
  libs/R-TypeLogic/Global/Systems/CMakeLists.txt
  libs/R-TypeLogic/Global/Systems/ElectricInvisibleEnemySystem.cpp
  libs/R-TypeLogic/Global/Systems/ElectricInvisibleEnemySystem.hpp
  libs/R-TypeLogic/Server/Systems/CMakeLists.txt
  libs/R-TypeLogic/Server/Systems/EnemiesGoRandom.cpp
  libs/R-TypeLogic/Server/Systems/EnemiesPatterns.cpp
  libs/R-TypeLogic/Server/Systems/EnemiesPatterns.hpp
  libs/Transisthor/Transisthor.cpp
  libs/Transisthor/Transisthor.hpp
  libs/Transisthor/TransisthorECSLogic/Client/Systems/SendToServer.hpp
  libs/Transisthor/TransisthorECSLogic/Server/Systems/SendToClient.cpp
  libs/Transisthor/TransisthorECSLogic/Server/Systems/SendToClient.hpp
  tests/unit_tests/Transisthor_tests/Transisthor_tests.cpp
  tests/unit_tests/libs_tests/ECS_tests/Systems_tests/EnemyGoRandom_System_test.cpp
  tests/unit_tests/libs_tests/GameEntityManipulation_tests/CreateEntitiesFunctions_tests/CreateEnemy_test.cpp
Labels: SFML, R-Type Game

#305 255 add mod solo
  Client/CMakeLists.txt
  Client/ClientRoom.cpp
  Client/ClientRoom.hpp
  Client/main.cpp
  libs/GraphicECS/SFML/Systems/SfObjectFollowEntitySystem.hpp
  libs/R-TypeLogic/EntityManipulation/CreateEntitiesFunctions/CreateAlliedProjectile.cpp
  libs/R-TypeLogic/EntityManipulation/CreateEntitiesFunctions/CreateAlliedProjectile.hpp
  libs/R-TypeLogic/EntityManipulation/CreateEntitiesFunctions/CreateEnemy.cpp
  libs/R-TypeLogic/EntityManipulation/CreateEntitiesFunctions/CreateEnemyProjectile.cpp
  libs/R-TypeLogic/Server/Systems/DeathLifeSystem.hpp
  libs/R-TypeLogic/Server/Systems/EnemyShootSystem.cpp
  tests/unit_tests/libs_tests/GameEntityManipulation_tests/CreateEntitiesFunctions_tests/CreateEnemy_test.cpp
Labels: Documentation, E.C.S., ECS Game Systems, R-Type Game

#323 322 updgrade writable entity
  Client/ButtonAction.cpp
  libs/GraphicECS/SFML/Systems/InputManagement.cpp
Labels: BUG

#326 325 - Fix the multiconnection bug and useless log
  Client/ClientRoom.cpp
  libs/Communicator/Communicator.cpp
  libs/R-TypeLogic/Global/Components/DeathComponent.hpp
  libs/R-TypeLogic/Global/Components/DestinationComponent.hpp
  libs/R-TypeLogic/Global/Components/EquipmentComponent.hpp
  libs/R-TypeLogic/Global/Components/InvinsibleComponent.hpp
  libs/R-TypeLogic/Global/Components/InvisibleComponent.hpp
  libs/R-TypeLogic/Global/Components/LifeComponent.hpp
  libs/R-TypeLogic/Global/Components/PositionComponent.hpp
  libs/R-TypeLogic/Global/Components/VelocityComponent.hpp
  libs/R-TypeLogic/Global/Systems/UpdateClockSystem.cpp
  libs/Transisthor/TransisthorECSLogic/Client/Systems/SendNewlyCreatedToServer.cpp
  libs/Transisthor/TransisthorECSLogic/Server/Systems/SendNewlyCreatedToClients.cpp
  libs/Transisthor/TransisthorECSLogic/Server/Systems/SendToClient.hpp
  tests/unit_tests/libs_tests/ECS_tests/Systems_tests/ShootEnemy_system_test.cpp
Labels: BUG

#328 BUG : the server close its self on Windows - Improve the build batch file.
  .gitignore
  build.bat
Labels: Architecture, BUG

#331 330 close window event doesn't close the client
  libs/GraphicECS/SFML/Systems/InputManagement.cpp
Labels: SFML, BUG

#318 316 create main menu
  Client/ButtonAction.cpp
  Client/ButtonAction.hpp
  Client/ClientRoom.cpp
  Client/ClientRoom.hpp
  Client/UserConnection.cpp
  libs/GraphicECS/SFML/Resources/GraphicsTextureResource.hpp
  libs/GraphicECS/SFML/Resources/MusicResource.hpp
  libs/GraphicECS/SFML/Resources/SoundResource.hpp
  libs/GraphicECS/SFML/Systems/DrawComponents.cpp
  libs/GraphicECS/SFML/Systems/MusicManagement.cpp
  libs/GraphicECS/SFML/Systems/SoundManagement.cpp
  libs/R-TypeLogic/EntityManipulation/ButtonManipulation/SharedResources/ButtonActionMap.hpp
  libs/R-TypeLogic/EntityManipulation/ButtonManipulation/SharedResources/MenuStates.hpp
Labels: SFML

#333 308: Select the good executable on Windows
  Server/RoomInstance.cpp
Labels: BUG

#332 327 create a boss
  Client/ClientRoom.cpp
  assets/EpiSprite/BossSpriteSheet.gif
  libs/GraphicECS/SFML/Resources/GraphicsTextureResource.hpp
  libs/GraphicECS/SFML/Systems/DrawComponents.cpp
  libs/R-TypeLogic/EntityManipulation/CreateEntitiesFunctions/CreateEnemy.cpp
  libs/R-TypeLogic/EntityManipulation/CreateEntitiesFunctions/CreateEnemy.hpp
  libs/R-TypeLogic/Global/Components/EnemyComponent.hpp
  libs/R-TypeLogic/Server/Systems/EnemiesPatterns.cpp
  libs/R-TypeLogic/Server/Systems/EnemyShootSystem.cpp
  libs/R-TypeLogic/Server/Systems/MobGenerationSystem.cpp
Labels: R-Type Game

#337 336 fix unexpected lag
  libs/R-TypeLogic/EntityManipulation/CreateEntitiesFunctions/CreateEnemy.cpp
  libs/R-TypeLogic/Server/Systems/EnemiesPatterns.cpp
  tests/unit_tests/libs_tests/ECS_tests/Systems_tests/ShootEnemy_system_test.cpp
Labels: BUG

#338 324 add input delay
  libs/Communicator/Receiver.cpp
  libs/Communicator/Sender.cpp
  libs/Database/Database.cpp
  libs/GraphicECS/SFML/Components/CMakeLists.txt
  libs/GraphicECS/SFML/Components/InputDelayComponent.hpp
  libs/GraphicECS/SFML/Systems/InputManagement.cpp
  libs/R-TypeLogic/EntityManipulation/CreateEntitiesFunctions/CreateEnemy.cpp
  libs/R-TypeLogic/Global/Systems/MovementSystem.cpp
  libs/R-TypeLogic/Server/Systems/EnemiesPatterns.cpp
  libs/R-TypeLogic/Server/Systems/MobGenerationSystem.cpp
  libs/Transisthor/Transisthor.cpp
  libs/Transisthor/TransisthorECSLogic/Client/Systems/SendToServer.hpp
  tests/unit_tests/libs_tests/SFML_tests/Systems/InputManagement_tests.cpp
Labels: BUG

#340 280 differentiate the background
  Client/ClientRoom.cpp
  libs/GraphicECS/SFML/Resources/GraphicsTextureResource.hpp
  libs/GraphicECS/SFML/Systems/CMakeLists.txt
  libs/GraphicECS/SFML/Systems/UpdateParallaxSystem.cpp
  libs/GraphicECS/SFML/Systems/UpdateParallaxSystem.hpp
  libs/R-TypeLogic/Global/SharedResources/GameLevel.cpp
  libs/R-TypeLogic/Global/SharedResources/GameLevel.hpp
  libs/R-TypeLogic/Global/Systems/DeathSystem.hpp
  libs/R-TypeLogic/Server/Systems/DeathLifeSystem.hpp
  libs/R-TypeLogic/Server/Systems/MobGenerationSystem.cpp
Labels: R-Type Game

#344 343 fix animation frequency
  libs/GraphicECS/SFML/Systems/AnimationSystem.cpp
Labels: BUG

#342 341 create text component
  libs/R-TypeLogic/Global/Components/CMakeLists.txt
  libs/R-TypeLogic/Global/Components/TextComponent.hpp
Labels: E.C.S.

#347 346 log in window always active
  Client/ClientRoom.cpp
Labels: BUG

#345 329 create lobby menu
  Client/ButtonAction.cpp
  Client/ButtonAction.hpp
  Client/ClientRoom.cpp
  Client/ClientRoom.hpp
  libs/GraphicECS/SFML/Systems/DrawComponents.cpp
  libs/R-TypeLogic/EntityManipulation/ButtonManipulation/SharedResources/ButtonActionMap.hpp
  libs/R-TypeLogic/EntityManipulation/ButtonManipulation/SharedResources/MenuStates.hpp
  libs/R-TypeLogic/EntityManipulation/CreateEntitiesFunctions/CreateButton.cpp
  libs/R-TypeLogic/EntityManipulation/CreateEntitiesFunctions/CreateButton.hpp
  tests/unit_tests/libs_tests/GameEntityManipulation_tests/CreateEntitiesFunctions_tests/CreateButton_tests.cpp
Labels: SFML

#350 349 use maccro to store textures path
  Client/CMakeLists.txt
  Client/ClientRoom.cpp
  Client/ClientRoom.hpp
  Client/UserConnection.cpp
  Client/UserConnection.hpp
  include/maccro.h
  libs/GraphicECS/SFML/CMakeLists.txt
  libs/GraphicECS/SFML/Systems/UpdateParallaxSystem.cpp
  libs/GraphicECS/SFML/Systems/UpdateParallaxSystem.hpp
Labels: SFML

#354 353 a button is drawn in a bad menu
  libs/GraphicECS/SFML/Systems/DrawComponents.cpp
Labels: SFML, BUG

#358 356 fix room name on button in lobby
  Client/ClientRoom.cpp
Labels: SFML, BUG

#362 359 create a back button in lobby to go to main menu
  Client/ButtonAction.cpp
  Client/ButtonAction.hpp
  Client/ClientRoom.cpp
  libs/R-TypeLogic/EntityManipulation/ButtonManipulation/SharedResources/ButtonActionMap.hpp
Labels: SFML

#366 355 room bug working
  Client/ButtonAction.cpp
  Client/ClientRoom.cpp
  Room/Room.cpp
  Server/Server.cpp
  libs/Communicator/Communicator.cpp
Labels: BUG

#376 375 coverage job fail on CI
  build_tests.sh
Labels: GitHub action, BUG

#367 365 inputs are sometimes disabled
  Client/ButtonAction.cpp
Labels: SFML, BUG

#377 363 disable window resizable
  libs/GraphicECS/SFML/Resources/RenderWindowResource.hpp
Labels: SFML, BUG

#369 351 fix velocity in solo mod
  Client/ClientRoom.cpp
  libs/GraphicECS/SFML/Systems/ApplyInputDelay.cpp
  libs/GraphicECS/SFML/Systems/ApplyInputDelay.hpp
  libs/GraphicECS/SFML/Systems/CMakeLists.txt
  libs/R-TypeLogic/Global/SharedResources/GameLevel.cpp
  libs/R-TypeLogic/Global/SharedResources/GameLevel.hpp
Labels: SFML, BUG

#381 380 the boss don't spawn even if you've killed every mob
  libs/R-TypeLogic/Global/SharedResources/GameLevel.hpp
  libs/R-TypeLogic/Server/Systems/MobGenerationSystem.cpp
Labels: BUG, R-Type Game

#383 374 rebase pseudo and password size management
  AdminPanel/AdminPanel.cpp
  Client/ClientRoom.cpp
  Client/UserConnection.cpp
  Room/Room.cpp
  Server/Server.cpp
  libs/Communicator/Communicator.cpp
  libs/Transisthor/Transisthor.cpp
  tests/unit_tests/Transisthor_tests/Transisthor_tests.cpp
Labels: BUG

#385 Projectiles on solo mod are now deleted
  libs/R-TypeLogic/Server/Systems/LifeTimeDeathSystem.hpp
Labels: BUG, R-Type Game

#387 Minor bug on kill count
  Client/ClientRoom.cpp
  libs/R-TypeLogic/Global/SharedResources/GameLevel.cpp
  libs/R-TypeLogic/Global/SharedResources/GameLevel.hpp
  libs/R-TypeLogic/Global/Systems/DeathSystem.hpp
Labels: BUG, R-Type Game

#390 384 fix lasts bug before delivery
  Client/ClientRoom.cpp
  Client/ClientRoom.hpp
  libs/Transisthor/TransisthorECSLogic/Server/Systems/SendToClient.hpp
Labels: BUG

#391 389 add a score for each player
  Room/Room.cpp
  libs/R-TypeLogic/Global/SharedResources/CMakeLists.txt
  libs/R-TypeLogic/Global/SharedResources/GlobalScore.cpp
  libs/R-TypeLogic/Global/SharedResources/GlobalScore.hpp
  libs/R-TypeLogic/Global/Systems/DeathSystem.hpp
  libs/R-TypeLogic/Server/Systems/DisconnectableSystem.cpp
Labels: R-Type Game

#392 378 add assets to the release
  .github/workflows/release.yml
  CMakeLists.txt
  LICENSE
  misc/windows/wix_licence.txt
Labels: GitHub action, GitHub Repository, Documentation, Cmake, Architecture

#396 393 update README.md
  README.md
Labels: Documentation

#399 397 implement a scoreboard
  AdminPanel/AdminPanel.cpp
  AdminPanel/AdminPanel.hpp
  Client/ClientRoom.cpp
  Server/Server.cpp
  Server/Server.hpp
  libs/Communicator/Communicator.cpp
  libs/Communicator/Communicator.hpp
  libs/Communicator/Receiver.cpp
  libs/Communicator/Receiver.hpp
  libs/Communicator/Sender.cpp
  libs/Communicator/Sender.hpp
Labels: Network, R-Type Game

#401 Update Readme with the new story
  README.md
Labels: Documentation, R-Type Game

#405 394 release on windows
  .github/workflows/release.yml
  AdminPanel/CMakeLists.txt
  CMakeLists.txt
  libs/ArgumentHandler/CMakeLists.txt
  libs/Communicator/CMakeLists.txt
  libs/Database/CMakeLists.txt
  libs/ECS/CMakeLists.txt
  libs/Error/CMakeLists.txt
  libs/GraphicECS/SFML/CMakeLists.txt
  libs/R-TypeLogic/EntityManipulation/ButtonManipulation/CMakeLists.txt
  libs/R-TypeLogic/EntityManipulation/CreateEntitiesFunctions/CMakeLists.txt
  libs/R-TypeLogic/Global/CMakeLists.txt
  libs/R-TypeLogic/Server/CMakeLists.txt
  libs/Transisthor/CMakeLists.txt
Labels: GitHub action, BUG

#388 361 create a menu to select between solo mod and multi mod
  AdminPanel/AdminPanel.cpp
  AdminPanel/AdminPanel.hpp
  Client/ButtonAction.cpp
  Client/ButtonAction.hpp
  Client/ClientRoom.cpp
  Client/ClientRoom.hpp
  Client/UserConnection.cpp
  Room/Room.cpp
  Room/Room.hpp
  Room/main.cpp
  Server/RoomInstance.cpp
  Server/RoomInstance.hpp
  Server/Server.cpp
  Server/Server.hpp
  libs/ArgumentHandler/ArgumentHandler.cpp
  libs/ArgumentHandler/ArgumentHandler.hpp
  libs/Communicator/Communicator.cpp
  libs/Communicator/Communicator.hpp
  libs/Communicator/Receiver.cpp
  libs/Communicator/Receiver.hpp
  libs/Communicator/Sender.cpp
  libs/Communicator/Sender.hpp
  libs/ECS/World/World.hpp
  libs/GraphicECS/SFML/Components/ControllerButtonInputComponent.hpp
  libs/GraphicECS/SFML/Resources/MusicResource.hpp
  libs/GraphicECS/SFML/Resources/RenderWindowResource.hpp
  libs/GraphicECS/SFML/Resources/SoundResource.hpp
  libs/GraphicECS/SFML/Systems/CMakeLists.txt
  libs/GraphicECS/SFML/Systems/DrawComponents.cpp
  libs/GraphicECS/SFML/Systems/DrawComponents.hpp
  libs/GraphicECS/SFML/Systems/InputManagement.cpp
  libs/GraphicECS/SFML/Systems/InputManagement.hpp
  libs/GraphicECS/SFML/Systems/MusicManagement.cpp
  libs/GraphicECS/SFML/Systems/SoundManagement.cpp
  libs/GraphicECS/SFML/Systems/UpdateLifeText.cpp
  libs/GraphicECS/SFML/Systems/UpdateLifeText.hpp
  libs/R-TypeLogic/EntityManipulation/ButtonManipulation/SharedResources/ButtonActionMap.hpp
  libs/R-TypeLogic/EntityManipulation/ButtonManipulation/SharedResources/MenuStates.hpp
  libs/R-TypeLogic/EntityManipulation/CreateEntitiesFunctions/CMakeLists.txt
  libs/R-TypeLogic/EntityManipulation/CreateEntitiesFunctions/CreateText.cpp
  libs/R-TypeLogic/EntityManipulation/CreateEntitiesFunctions/CreateText.hpp
  libs/R-TypeLogic/Global/Components/LayerLvL.hpp
  libs/R-TypeLogic/Global/Components/VelocityComponent.hpp
  libs/R-TypeLogic/Global/SharedResources/GameClock.cpp
  libs/R-TypeLogic/Global/Systems/MovementSystem.cpp
  libs/Transisthor/TransisthorECSLogic/Client/Systems/SendToServer.cpp
Labels: Architecture, Network, SFML, functions to create entities, BUG, R-Type Game, Game Design

#407 Fix collidable system with deads entities #406
  libs/R-TypeLogic/Server/Systems/CollidableSystem.cpp
Labels: BUG

#412 409 bug display in solo mod
  AdminPanel/main.cpp
  Client/ClientRoom.cpp
  Client/main.cpp
  Room/main.cpp
  Server/main.cpp
  libs/ArgumentHandler/ArgumentHandler.cpp
  libs/ArgumentHandler/ArgumentHandler.hpp
  libs/GraphicECS/SFML/Systems/UpdateLifeText.cpp
Labels: R-Type Game
